# Generated by Django 4.1 on 2022-09-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_carrodecompras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodeservicio', models.CharField(choices=[('Activo', 'Activo'), ('Completa', 'Completa')], max_length=10, verbose_name='Seleccione el tipo de servicio')),
                ('factura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.generar', verbose_name='factura')),
            ],
        ),
    ]
