# Generated by Django 4.1 on 2022-09-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_compras_estado_compras_insumo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='total',
            field=models.IntegerField(default=0.0, verbose_name='Total'),
        ),
    ]
