# Generated by Django 4.1 on 2022-09-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_compras_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='total',
        ),
    ]
