# Generated by Django 4.1 on 2022-09-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_alter_insumo_marca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='stock',
        ),
    ]
