# Generated by Django 4.1 on 2022-09-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0005_alter_marca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
