# Generated by Django 4.0.4 on 2022-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0007_alter_insumo_nombre_alter_marca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.PositiveIntegerField(),
        ),
    ]
