# Generated by Django 4.1 on 2022-09-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0008_alter_insumo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Anulado', 'Anulado')], default='Activo', max_length=10, verbose_name='Estado'),
        ),
    ]
