# Generated by Django 4.1 on 2022-08-31 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=45, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=13, unique=True, verbose_name='Numero de celular')),
            ],
        ),
        migrations.CreateModel(
            name='Vehículo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('modelo', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=15, verbose_name='Color del vehículo')),
                ('estado', models.CharField(choices=[('E', 'Exelente (E)'), ('R', 'Regular (R)'), ('B', 'Bien (B)'), ('M', 'Mal (M)')], max_length=10, verbose_name='Estado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
